import type {
  Company,
  Contact,
  DataSource,
  FollowUpTask,
  MarketSignal,
  Opportunity,
} from "@/lib/domain";

export const DEMO_COMPANIES: Company[] = [
  {
    id: "cmp-aurora",
    name: "Aurora Automotive Interiors GmbH",
    domain: "aurora-interiors.demo",
    industry: "汽车内饰",
    region: "德国 · 巴伐利亚",
    employeeRange: "201-500",
    description: "汽车座椅面套与柔性内饰件演示企业",
    technologies: ["CAD", "MES", "CNC Cutting"],
    isDemo: true,
  },
  {
    id: "cmp-nordtex",
    name: "NordTex Mobility SE",
    domain: "nordtex.demo",
    industry: "柔性材料裁切",
    region: "德国 · 北莱茵",
    employeeRange: "501-1000",
    description: "面向商用车的复合材料零部件演示企业",
    technologies: ["SAP", "PLM", "Laser Cutting"],
    isDemo: true,
  },
  {
    id: "cmp-packform",
    name: "PackForm Polska",
    domain: "packform.demo",
    industry: "包装设备",
    region: "波兰 · 弗罗茨瓦夫",
    employeeRange: "101-200",
    description: "可持续包装与自动化产线演示企业",
    technologies: ["ERP", "PLC", "Robotics"],
    isDemo: true,
  },
  {
    id: "cmp-iberbag",
    name: "IberBag Manufacturing",
    domain: "iberbag.demo",
    industry: "箱包制造",
    region: "西班牙 · 瓦伦西亚",
    employeeRange: "201-500",
    description: "旅行箱包柔性生产演示企业",
    technologies: ["Gerber", "ERP", "CAD"],
    isDemo: true,
  },
  {
    id: "cmp-vietstep",
    name: "VietStep Footwear",
    domain: "vietstep.demo",
    industry: "鞋材加工",
    region: "越南 · 胡志明市",
    employeeRange: "1001-5000",
    description: "运动鞋鞋面与鞋垫加工演示企业",
    technologies: ["ERP", "CAD", "Die Cutting"],
    isDemo: true,
  },
  {
    id: "cmp-mechaflex",
    name: "MechaFlex Systems",
    domain: "mechaflex.demo",
    industry: "工业自动化",
    region: "捷克 · 布尔诺",
    employeeRange: "51-100",
    description: "工业自动化集成演示企业",
    technologies: ["Siemens PLC", "ROS", "OPC UA"],
    isDemo: true,
  },
];

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "ct-lena",
    companyId: "cmp-aurora",
    name: "Lena Hoffmann",
    title: "Director of Production",
    seniority: "director",
    location: "Munich, Germany",
    linkedinUrl: "https://www.linkedin.com/",
    needsEnrichment: true,
    source: "Apollo 演示结果",
    isDemo: true,
  },
  {
    id: "ct-markus",
    companyId: "cmp-nordtex",
    name: "Markus Weber",
    title: "Head of Procurement",
    seniority: "head",
    location: "Cologne, Germany",
    linkedinUrl: "https://www.linkedin.com/",
    needsEnrichment: true,
    source: "Apollo 演示结果",
    isDemo: true,
  },
  {
    id: "ct-anna",
    companyId: "cmp-packform",
    name: "Anna Kowalska",
    title: "Plant Manager",
    seniority: "manager",
    location: "Wrocław, Poland",
    needsEnrichment: true,
    source: "公开名录演示数据",
    isDemo: true,
  },
  {
    id: "ct-carlos",
    companyId: "cmp-iberbag",
    name: "Carlos Ruiz",
    title: "COO",
    seniority: "c_suite",
    location: "Valencia, Spain",
    needsEnrichment: true,
    source: "展会名录演示数据",
    isDemo: true,
  },
];

export const DEMO_SIGNALS: MarketSignal[] = [
  {
    id: "sig-001",
    companyId: "cmp-aurora",
    companyName: "Aurora Automotive Interiors GmbH",
    title: "新增柔性材料自动裁切产线项目",
    sourceName: "企业官网 · 演示数据",
    sourceUrl: "https://example.com/demo-source",
    industry: "汽车内饰",
    region: "德国",
    summary: "新工厂招聘自动化工程师，并提及座椅面套裁切工序数字化改造。",
    keywords: ["自动裁切", "新工厂", "MES"],
    intensity: 93,
    urgency: 88,
    confidence: 91,
    score: 94,
    level: "HIGH",
    recommendation: "48小时内联系生产总监，提供汽车内饰裁切效率测算。",
    publishedAt: "2026-08-31T07:20:00.000Z",
    isDemo: true,
    x: 48,
    y: 43,
  },
  {
    id: "sig-002",
    companyId: "cmp-nordtex",
    companyName: "NordTex Mobility SE",
    title: "复合材料损耗率优化招标预告",
    sourceName: "行业协会 · 演示数据",
    sourceUrl: "https://example.com/demo-source",
    industry: "柔性材料裁切",
    region: "德国",
    summary: "计划优化复合材料排版与裁切，目标将材料损耗降低8%以上。",
    keywords: ["材料损耗", "招标", "排版优化"],
    intensity: 89,
    urgency: 92,
    confidence: 85,
    score: 91,
    level: "HIGH",
    recommendation: "准备材料利用率对标案例，优先覆盖采购与工艺负责人。",
    publishedAt: "2026-08-31T05:40:00.000Z",
    isDemo: true,
    x: 54,
    y: 49,
  },
  {
    id: "sig-003",
    companyId: "cmp-packform",
    companyName: "PackForm Polska",
    title: "包装产线扩产并招聘PLC工程师",
    sourceName: "招聘信息 · 演示数据",
    sourceUrl: "https://example.com/demo-source",
    industry: "包装设备",
    region: "波兰",
    summary: "连续发布PLC和设备维护岗位，推测新产线将在下一季度投产。",
    keywords: ["扩产", "PLC", "设备采购"],
    intensity: 76,
    urgency: 74,
    confidence: 82,
    score: 81,
    level: "MEDIUM",
    recommendation: "确认扩产节拍目标，寻找工厂负责人和自动化经理。",
    publishedAt: "2026-08-30T15:10:00.000Z",
    isDemo: true,
    x: 36,
    y: 58,
  },
  {
    id: "sig-004",
    companyId: "cmp-iberbag",
    companyName: "IberBag Manufacturing",
    title: "箱包小批量定制业务增长",
    sourceName: "新闻媒体 · 演示数据",
    sourceUrl: "https://example.com/demo-source",
    industry: "箱包制造",
    region: "西班牙",
    summary: "宣布增加小批量定制产品线，现有刀模切换可能成为柔性生产瓶颈。",
    keywords: ["小批量", "柔性生产", "定制"],
    intensity: 72,
    urgency: 63,
    confidence: 78,
    score: 77,
    level: "MEDIUM",
    recommendation: "以免刀模快速换款为切入点，预约10分钟效率诊断。",
    publishedAt: "2026-08-30T10:30:00.000Z",
    isDemo: true,
    x: 68,
    y: 34,
  },
  {
    id: "sig-005",
    companyId: "cmp-vietstep",
    companyName: "VietStep Footwear",
    title: "鞋面自动化升级可行性调研",
    sourceName: "展会公开名录 · 演示数据",
    sourceUrl: "https://example.com/demo-source",
    industry: "鞋材加工",
    region: "越南",
    summary: "展会登记关注智能排版、视觉定位与多层裁切方案。",
    keywords: ["鞋面", "视觉定位", "多层裁切"],
    intensity: 84,
    urgency: 70,
    confidence: 73,
    score: 79,
    level: "MEDIUM",
    recommendation: "发送鞋材应用视频并询问日产量与材料层数。",
    publishedAt: "2026-08-29T08:45:00.000Z",
    isDemo: true,
    x: 29,
    y: 39,
  },
  {
    id: "sig-006",
    companyId: "cmp-mechaflex",
    companyName: "MechaFlex Systems",
    title: "寻找数字化裁切设备合作伙伴",
    sourceName: "Webhook · 演示数据",
    sourceUrl: "https://example.com/demo-source",
    industry: "工业自动化",
    region: "捷克",
    summary: "系统集成商希望补充柔性材料加工产品线，存在渠道合作可能。",
    keywords: ["系统集成", "渠道合作", "设备"],
    intensity: 67,
    urgency: 58,
    confidence: 69,
    score: 71,
    level: "LOW",
    recommendation: "先评估渠道覆盖和技术服务能力，再安排伙伴会议。",
    publishedAt: "2026-08-28T13:00:00.000Z",
    isDemo: true,
    x: 73,
    y: 65,
  },
];

export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-aurora",
    companyId: "cmp-aurora",
    companyName: "Aurora Automotive Interiors GmbH",
    primaryContactId: "ct-lena",
    primaryContactName: "Lena Hoffmann",
    contactIds: ["ct-lena"],
    sourceSignalId: "sig-001",
    name: "座椅面套智能裁切升级",
    source: "市场雷达",
    industry: "汽车内饰",
    score: 94,
    estimatedAmount: 1280000,
    currency: "CNY",
    probability: 72,
    stage: "NEED_CONFIRMED",
    owner: "林晓",
    nextAction: "发送产能测算模板",
    expectedCloseDate: "2026-10-28",
    lastActivityAt: "2026-08-31T06:30:00.000Z",
    riskTags: ["决策链未覆盖"],
    isDemo: true,
    stageHistory: [],
  },
  {
    id: "opp-nordtex",
    companyId: "cmp-nordtex",
    companyName: "NordTex Mobility SE",
    primaryContactId: "ct-markus",
    primaryContactName: "Markus Weber",
    contactIds: ["ct-markus"],
    sourceSignalId: "sig-002",
    name: "复合材料利用率提升项目",
    source: "行业协会",
    industry: "柔性材料裁切",
    score: 91,
    estimatedAmount: 860000,
    currency: "CNY",
    probability: 58,
    stage: "CONTACTED",
    owner: "陈拓",
    nextAction: "确认技术评估人",
    expectedCloseDate: "2026-11-15",
    lastActivityAt: "2026-08-30T09:20:00.000Z",
    riskTags: ["竞品已接触"],
    isDemo: true,
    stageHistory: [],
  },
  {
    id: "opp-packform",
    companyId: "cmp-packform",
    companyName: "PackForm Polska",
    primaryContactId: "ct-anna",
    primaryContactName: "Anna Kowalska",
    contactIds: ["ct-anna"],
    sourceSignalId: "sig-003",
    name: "包装产线自动化扩产",
    source: "招聘信号",
    industry: "包装设备",
    score: 81,
    estimatedAmount: 540000,
    currency: "CNY",
    probability: 41,
    stage: "TO_CONTACT",
    owner: "林晓",
    nextAction: "生成英文开发信",
    expectedCloseDate: "2026-12-05",
    lastActivityAt: "2026-08-29T12:10:00.000Z",
    riskTags: ["尚未触达"],
    isDemo: true,
    stageHistory: [],
  },
  {
    id: "opp-iberbag",
    companyId: "cmp-iberbag",
    companyName: "IberBag Manufacturing",
    primaryContactId: "ct-carlos",
    primaryContactName: "Carlos Ruiz",
    contactIds: ["ct-carlos"],
    sourceSignalId: "sig-004",
    name: "小批量免刀模裁切项目",
    source: "新闻信号",
    industry: "箱包制造",
    score: 77,
    estimatedAmount: 420000,
    currency: "CNY",
    probability: 33,
    stage: "QUALIFY",
    owner: "陈拓",
    nextAction: "补充工厂产能信息",
    expectedCloseDate: "2027-01-12",
    lastActivityAt: "2026-08-27T08:00:00.000Z",
    riskTags: ["信息不足", "7天未推进"],
    isDemo: true,
    stageHistory: [],
  },
];

export const DEMO_TASKS: FollowUpTask[] = [
  {
    id: "task-001",
    opportunityId: "opp-aurora",
    opportunityName: "座椅面套智能裁切升级",
    title: "发送产能测算模板",
    description: "附上汽车内饰材料利用率基准",
    dueAt: "2026-08-31T09:30:00.000Z",
    status: "PENDING",
    priority: "high",
    assignee: "林晓",
  },
  {
    id: "task-002",
    opportunityId: "opp-nordtex",
    opportunityName: "复合材料利用率提升项目",
    title: "确认技术评估人与采购时间表",
    dueAt: "2026-08-31T13:00:00.000Z",
    status: "PENDING",
    priority: "high",
    assignee: "陈拓",
  },
  {
    id: "task-003",
    opportunityId: "opp-packform",
    opportunityName: "包装产线自动化扩产",
    title: "发送英文首次触达邮件",
    dueAt: "2026-09-01T02:00:00.000Z",
    status: "PENDING",
    priority: "medium",
    assignee: "林晓",
  },
  {
    id: "task-004",
    opportunityId: "opp-iberbag",
    opportunityName: "小批量免刀模裁切项目",
    title: "补全企业生产规模",
    dueAt: "2026-08-29T07:00:00.000Z",
    status: "PENDING",
    priority: "medium",
    assignee: "陈拓",
  },
];

export const DEMO_DATA_SOURCES: DataSource[] = [
  {
    id: "ds-apollo",
    name: "Apollo",
    type: "apollo",
    status: "unconfigured",
    configured: false,
    enabled: false,
    discovered: 0,
    usageCurrent: 0,
    usageLimit: 100,
  },
  {
    id: "ds-association",
    name: "行业协会官方网站",
    type: "association",
    status: "connected",
    configured: true,
    enabled: true,
    lastScannedAt: "2026-08-31T07:10:00.000Z",
    discovered: 18,
    usageCurrent: 328,
  },
  {
    id: "ds-exhibition",
    name: "展会公开名录",
    type: "exhibition",
    status: "connected",
    configured: true,
    enabled: true,
    lastScannedAt: "2026-08-31T06:50:00.000Z",
    discovered: 12,
    usageCurrent: 156,
  },
  {
    id: "ds-website",
    name: "企业官网",
    type: "website",
    status: "connected",
    configured: true,
    enabled: true,
    lastScannedAt: "2026-08-31T07:25:00.000Z",
    discovered: 31,
    usageCurrent: 712,
  },
  {
    id: "ds-jobs",
    name: "招聘信息",
    type: "jobs",
    status: "connected",
    configured: true,
    enabled: true,
    lastScannedAt: "2026-08-31T07:02:00.000Z",
    discovered: 24,
    usageCurrent: 481,
  },
  {
    id: "ds-news",
    name: "新闻媒体",
    type: "news",
    status: "paused",
    configured: true,
    enabled: false,
    lastScannedAt: "2026-08-30T23:10:00.000Z",
    discovered: 9,
    usageCurrent: 93,
  },
  {
    id: "ds-qcc",
    name: "企查查类企业数据",
    type: "qcc",
    status: "unconfigured",
    configured: false,
    enabled: false,
    discovered: 0,
    usageCurrent: 0,
  },
  {
    id: "ds-csv",
    name: "手动 CSV 导入",
    type: "csv",
    status: "paused",
    configured: true,
    enabled: false,
    discovered: 0,
    usageCurrent: 0,
  },
  {
    id: "ds-webhook",
    name: "Webhook",
    type: "webhook",
    status: "connected",
    configured: true,
    enabled: true,
    lastScannedAt: "2026-08-31T05:22:00.000Z",
    discovered: 3,
    usageCurrent: 27,
  },
];

export const TREND_SERIES = {
  "7d": [
    { label: "08/25", automation: 62, cutting: 55, automotive: 66, packaging: 41 },
    { label: "08/26", automation: 65, cutting: 58, automotive: 68, packaging: 43 },
    { label: "08/27", automation: 64, cutting: 63, automotive: 72, packaging: 45 },
    { label: "08/28", automation: 71, cutting: 67, automotive: 75, packaging: 48 },
    { label: "08/29", automation: 73, cutting: 72, automotive: 79, packaging: 52 },
    { label: "08/30", automation: 78, cutting: 76, automotive: 83, packaging: 55 },
    { label: "今天", automation: 82, cutting: 84, automotive: 88, packaging: 59 },
  ],
  "30d": [
    { label: "第1周", automation: 51, cutting: 48, automotive: 58, packaging: 38 },
    { label: "第2周", automation: 59, cutting: 56, automotive: 64, packaging: 43 },
    { label: "第3周", automation: 68, cutting: 69, automotive: 73, packaging: 49 },
    { label: "第4周", automation: 82, cutting: 84, automotive: 88, packaging: 59 },
  ],
  "90d": [
    { label: "6月", automation: 44, cutting: 42, automotive: 51, packaging: 36 },
    { label: "7月", automation: 63, cutting: 61, automotive: 69, packaging: 45 },
    { label: "8月", automation: 82, cutting: 84, automotive: 88, packaging: 59 },
  ],
};
