from __future__ import annotations

from enum import Enum


class MachineState(str, Enum):
    IDLE = "IDLE"
    INIT = "INIT"
    SELF_CALIBRATION = "SELF_CALIBRATION"
    CALIBRATION_OK = "CALIBRATION_OK"
    LOAD_JOB = "LOAD_JOB"
    WAIT_MATERIAL = "WAIT_MATERIAL"
    ACQUIRE_IMAGE = "ACQUIRE_IMAGE"
    PREPROCESS = "PREPROCESS"
    MATCHING = "MATCHING"
    REGISTRATION = "REGISTRATION"
    DEFORMATION_ESTIMATION = "DEFORMATION_ESTIMATION"
    COMPENSATION_READY = "COMPENSATION_READY"
    WAIT_PLC_ACK = "WAIT_PLC_ACK"
    PUNCH_ALLOWED = "PUNCH_ALLOWED"
    POST_INSPECTION = "POST_INSPECTION"
    ONLINE_UPDATE = "ONLINE_UPDATE"
    PROJECTOR_INIT = "PROJECTOR_INIT"
    PROJECTOR_READY = "PROJECTOR_READY"
    PROJECTOR_CALIBRATION = "PROJECTOR_CALIBRATION"
    PROJECTOR_CALIBRATION_OK = "PROJECTOR_CALIBRATION_OK"
    PROJECTION_RENDER = "PROJECTION_RENDER"
    PROJECTION_PREVIEW = "PROJECTION_PREVIEW"
    PROJECTION_ALIGNMENT = "PROJECTION_ALIGNMENT"
    PROJECTION_FEEDBACK = "PROJECTION_FEEDBACK"
    PROJECTION_OK = "PROJECTION_OK"
    PROJECTION_FAILED = "PROJECTION_FAILED"
    ALARM = "ALARM"
    EMERGENCY_STOP = "EMERGENCY_STOP"


STATE_CODES = {state: idx for idx, state in enumerate(MachineState)}
